

name: Static analysis
on:
  - push
  - pull_request
permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq coccinelle

      - name: Confirm coccinelle output is clean
        run: |
          ./coccinelle/run-coccinelle.sh -i
          git diff --exit-code

      - name: Confirm apparmor profile is up to date
        run: |
          cd config/apparmor/
          ./lxc-generate-aa-rules.py container-rules.base > container-rules
          git diff --exit-code
