#!/bin/sh
#
# Update the hostname in the cloned container's scripts
#
# Copyright ©  2013 Oracle.
#
# This library is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2, as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

# Note that /etc/hostname is updated by lxc itself
for file in \
    $LXC_ROOTFS_MOUNT/etc/sysconfig/network \
    $LXC_ROOTFS_MOUNT/etc/sysconfig/network-scripts/ifcfg-* \
    $LXC_ROOTFS_MOUNT/etc/hosts ;
do
    if [ -f $file ]; then
        sed -i "s|$LXC_SRC_NAME|$LXC_NAME|" $file
    fi
done
exit 0
