#!/bin/sh

set -e

i=0
while true; do
	eval "bridge=\$LXC_CRIU_BRIDGE$i"
	eval "veth=\$LXC_CRIU_VETH$i"

	if [ -z "$bridge" ] || [ -z "$veth" ]; then
		exit 0
	fi

	if [ "$CRTOOLS_SCRIPT_ACTION" = "network-lock" ]; then
		brctl delif $bridge $veth
	fi

	if [ "$CRTOOLS_SCRIPT_ACTION" = "network-unlock" ]; then
		brctl addif $bridge $veth
		ifconfig $veth 0.0.0.0 up
	fi

	i=$((i+1))
done

exit 1
