name: Simple test build
on:
  - push
  - pull_request
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - gcc
          - clang
        os:
          - ubuntu-18.04
          - ubuntu-20.04
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq gcc clang
          sudo apt-get install -qq libapparmor-dev libcap-dev libseccomp-dev libselinux1-dev linux-libc-dev libpam0g-dev docbook2x

      - name: Compiler version
        env:
          CC: ${{ matrix.compiler }}
        run: |
          ${CC} --version

      - name: Kernel version
        run: |
          uname -a

      - name: Mount table
        run: |
          findmnt

      - name: Build
        env:
          CC: ${{ matrix.compiler }}
        run: |
          # Configure
          export CFLAGS="-Wall -Werror"
          export LDFLAGS="-pthread -lpthread"
          ./autogen.sh

          BUILD="$(pwd)/build"
          SAN_BUILD="$(pwd)/san_build"
          mkdir -p "${BUILD}" "${SAN_BUILD}"
          cd "${BUILD}"
          ../configure --enable-tests --with-distro=unknown

          # Build
          make -j4
          make DESTDIR="${BUILD}/install" install

          cd "${SAN_BUILD}"
          CFLAGS="$CFLAGS -fsanitize=address,undefined" ../configure --disable-no-undefined --enable-pam --enable-tests --with-distro=unknown
          make -j4
          make DESTDIR="${SAN_BUILD}/install" install
